# Generated by Django 4.1.7 on 2023-03-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='departments/%Y/%m', verbose_name='Imagem'),
        ),
    ]
