# Generated by Django 4.1.7 on 2023-04-02 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0003_department_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsold',
            name='data',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='products',
        ),
        migrations.AddField(
            model_name='productsold',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Valor (em centavos)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsold',
            name='sale',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products_sold', to='sales.sale', verbose_name='Produto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsold',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_sold', to='sales.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
