# Generated by Django 4.1.7 on 2023-04-06 23:11

import Core.forms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_price_promotional_value_alter_price_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='its_in_the_banner',
            field=models.BooleanField(default=False, verbose_name='Está no Banner ?'),
        ),
        migrations.AlterField(
            model_name='price',
            name='promotional_value',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[Core.forms.validators.validate_positive_number], verbose_name='Valor promocional (em centavos)'),
        ),
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.PositiveIntegerField(validators=[Core.forms.validators.validate_positive_number], verbose_name='Valor (em centavos)'),
        ),
        migrations.AlterField(
            model_name='productsold',
            name='price',
            field=models.PositiveIntegerField(validators=[Core.forms.validators.validate_positive_number], verbose_name='Valor (em centavos)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_value',
            field=models.PositiveIntegerField(validators=[Core.forms.validators.validate_positive_number], verbose_name='Valor total (em centavos)'),
        ),
    ]
