# Generated by Django 4.1.7 on 2023-04-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sales', '0008_product_its_in_the_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(default='', upload_to='departments/%Y/%m', verbose_name='Imagem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='products/%Y/%m', verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
